### ISSUE TITLE
Doesn't work with Tor Browser

### ISSUE THREAD

**Issue by ptomaszek** [ptomaszek/dummy-form-filler#10]
The plugin's icon isn't showing up in the Tor Browser (tested with the stable release 4.5.* [FF 31 ESR] and the alpha 5.* [FF 38 ESR]).

The plugin seems to be installed (Menu -> 'Customize' -> 'Restore Defaults' shows the plugin entry but without the icon).

Possible workaround: wire up a key shortcut as mentioned by m1ndh4ck .

**Comment by ptomaszek** [comment]
Adding a shortcut doesn't work.

**Comment by gmng** [comment]
Will you fix this or do you have a solution on this issue? 
https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/hotkeys

**Comment by ptomaszek** [comment]
Hi, 
Adding a hotkey didn't help. No other solution on the horizon.

About radio buttons - this could be possible only if #12 is solved first. To tell the truth I cannot promise any dates. Would be great if someone else could start working on that.

**Comment by gmng** [comment]
OK. I have no coding skills unfortunately. One of my favorite add-ons, it was a good idea to code it and it has no alternative. Thank you!

**Comment by gmng** [comment]
Maybe something is disabled in the about:config option in TorBrowser and it prevents to place the icon in the toolbar.

**Comment by gmng** [comment]
"One click to populate HTML forms with dummy data. Works out of the box."


You should use the "fill" word instead of populate. It means something else. 

It should look like 

"One click to fill HTML forms with dummy data. Works out of the box."

**Comment by gmng** [comment]
Any news on this add-on to make it working /w TorBrowser?

**Comment by ptomaszek** [comment]
Yes. The newest version 0.13.2 is working with Tor.

Thanks for getting back on this. Otherwise, nothing would have changed.

**Comment by gmng** [comment]
Awsome, You are genius! Thank you!
