### ISSUE TITLE
Make it work with chosen

### ISSUE THREAD

**Issue by DrowningElysium** [ptomaszek/dummy-form-filler#14]
Hello, 

We are using chosen for a lot of select boxes in our project, the problem is that these have a textbox to make search possible. Your plugin will fill these and make it not possible to auto select one or have one pre selected.

**Comment by krjohnston** [comment]
We are using select2 for select boxes and the the hidden select items get set and sent in the post, but not in the display ul (until you select another item and then it populates with all the selected items).

The other problem is that one select box has about 2000 options and around half of them get selected. A limit of maybe 5 or 10 would be very useful.

**Comment by ptomaszek** [comment]
The plugin may - and in this case it does - not work with HTML forms build on top of custom libraries like jQuery.

I can only encourage you to create a fork and make amendments that will suit your needs.
If you decide to go for it but need some kind of starting developer's 'howto', let me know.
