### ISSUE TITLE
Add option to set a fixed password

### ISSUE THREAD

**Issue by dedeibel** [ptomaszek/dummy-form-filler#15]
I would be cool if you could specify a global password that will be used for password fields so you can create user accounts that will be usable in further steps.

**Comment by dedeibel** [comment]
Cool plugin btw!

**Comment by dedeibel** [comment]
Found out 0Pa$$4uM^t3 is always the password. This helps but there might be the need to change it for other password requirements.

**Comment by ptomaszek** [comment]
Hey Benjamin,

First - I'm sorry for not answering to your first message - knowing earlier about `0Pa$$4uM^t3` could save you some time, I guess.

Second - yeah, there's this task #12 which is about making the plugin configurable and your idea is valid in its context, so let's keep both the issues open. Just keep in mind I'm not planning to get back to the plugin development very soon.

Thanks for your interest and kind words!

**Comment by dedeibel** [comment]
Thanks for the response. I'll close it then and mention the password briefly in #12

**Comment by ptomaszek** [comment]
Hi,

Just want to let you know about the recent update - now you can specify a custom password for _password_ fields.
Visit _about:addons_, find the extention, then click **Options** and there you have it.

**Comment by dedeibel** [comment]
Thank you very much.
