### ISSUE TITLE
Doesn't fire onChanged events, breaks client form validation

### ISSUE THREAD

**Issue by hackel** [ptomaszek/dummy-form-filler#16]
I've only tested this on Firefox.  When using javascript for client-side validation (like Angular), using this extension to auto-fill the form doesn't trigger an onChanged event, therefore, in the case of Angular, the form control's model doesn't get updated with the new value, and validation errors persist as if nothing had been entered into the field.  This means I have to go into each field that has a validation constraint and manually change the value (e.g. hit space/backspace) before it will be accepted by the validation and allow the form to submit.

While this may be a browser-based bug, it has persisted for over a decade and is unlikely to be fixed any time soon, so it would be great if this extension could manually fire the change events whenever it changes an input field.

**Comment by ptomaszek** [comment]
Hey Ryan,
 
Thanks for detailed explanation and valid remarks.
I believe the fix should be easy but please give me a couple of days to find the time.

In the meantime I would appreciate if you could paste here some publicly available url (preferably Angular-based page) that seems to be wrongly managed by the plugin.

**Comment by hackel** [comment]
It's happening on the login page for one of my apps, here: http://quirks.com/login
The issue could theoretically be fixed in Angular too, but I believe it is framework agnostic and specific to Firefox.  Thanks!

**Comment by ptomaszek** [comment]
Fixed.

Appropriate DOM event is being triggered. Checked on you page.

Again thanks for raising the issue as the fix may help other devs.
Happy coding and good luck with quirk's!

**Comment by hackel** [comment]
Brilliant, thanks for that @ptomaszek!  And thanks for the great extension.  I've used a lot of these on both FF and Chrome over the years, and this is definitely the best and simplest of them all.
