### ISSUE TITLE
Keyboard Shortcut

### ISSUE THREAD

**Issue by janissbinder** [ptomaszek/dummy-form-filler#17]
Would be nice to fill out a form with a keyboard shortcut.

**Comment by ptomaszek** [comment]
Hi Janiss,

Good point. 
The newest release 1.2.2 brings a shortcut under **Alt+Shift+D**.

Works well in Chrome but not always in Firefox (FF still struggles to fully support WebExtensions which is the technology DFF takes advantage of).
