### ISSUE TITLE
Not just dummy

### ISSUE THREAD

**Issue by maverick74** [ptomaszek/dummy-form-filler#18]
Here's what i would suggest:

1. Auto Fill Forms on page load option (no clicks)
2. Allow me to save/delete/update the data of the saved forms really easy
3. Ability to save and restore the forms auto-complete data

**Comment by ptomaszek** [comment]
Thanks.

1. Populating data is only one click (or button shortcut) away. I believe it's convenient enough.
2. That would be cool but there are already tools suiting such requirement. You can do something like this:
   - use DFF to generate dummy data for the first time
   - amend data
   - use another extension that saves and restores forms
3. I guess point 2 covers that.


Feel free to fork the code. I'll be happy to merge any configurable features.
