### ISSUE TITLE
Honour maxlength in <textarea>

### ISSUE THREAD

**Issue by kAlvaro** [ptomaszek/dummy-form-filler#22]
The add-on does not seem to honour the `maxlength` attribute in `<textarea>` tags. That leads to validation errors that are tedious to fix. (I presume it doesn't honour `minlength` either.)

Reference:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attr-maxlength
- https://caniuse.com/#feat=maxlength

**Comment by ptomaszek** [comment]
Fixed in 1.3.0
