### ISSUE TITLE
`<select>` with empty value and non-emtpy tag are not populated

### ISSUE THREAD

**Issue by kAlvaro** [ptomaszek/dummy-form-filler#23]
A select list like this is ignored:

```
<select name="country">
    <option value="">(pick one)</option>
    <option value="us">United States</option>
    <option value="ca">Canada</option>
</select>
```

I presume the logic is that it already has a value but `(pick one)` is not an actual value and will not be sent to server. I think that if `value` attribute is present it should have priority over the tag value.

**Comment by ptomaszek** [comment]
Please download https://github.com/ptomaszek/dummy-form-filler/blob/master/show.html and add your select there. It should work.

But if the select still doesn't work on some other page, please provide related url/HTML so I could analyze it.

**Comment by kAlvaro** [comment]
Interesting... It works fine there. Please let me check if I can remember what site I was working on when I reported the issue.

**Comment by kAlvaro** [comment]
Funny. It fails in `show.html` with this other select:

```
    <select name="foo" required="required">
        <option value="">(elige un producto)</option>
        <option value="44">One</option>
        <option value="45">Two</option>
    </select>
```

Here's a Codepen that also exhibits the issue: https://codepen.io/anon/pen/vbEpjE
Though I'm not entirely sure whether it should work in iframes.

**Comment by ptomaszek** [comment]
It took me some time, but I finally fixed it.

Please check if version **1.3.1** brings desired change.
It won't work in iframes, but I added your example to https://rawgit.com/ptomaszek/dummy-form-filler/master/show.html (`Select single 3`)
