### ISSUE TITLE
DummyFormFiller is not defined

### ISSUE THREAD

**Issue by kylewhat** [ptomaszek/dummy-form-filler#24]
/Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/npghpiokpleaiakfmalkmhkcloahfnad/1.3.0_0/js/main.js:6 ReferenceError: DummyFormFiller is not defined
    at /Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/npghpiokpleaiakfmalkmhkcloahfnad/1.3.0_0/js/main.js:3
(anonymous) @ /Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/npghpiokpleaiakfmalkmhkcloahfnad/1.3.0_0/js/main.js:6

**Comment by ptomaszek** [comment]
Do you still face the issue?

If so, please write the version of Chrome you're using.
