### ISSUE TITLE
Remove source map declaration

### ISSUE THREAD

**Issue by hackel** [ptomaszek/dummy-form-filler#25]
Whenever I load any web page, I get the following error:
```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://125f886f-7ffb-47c2-b040-c6deae618cc2/js-ext/chance.min.js
Source Map URL: chance.min.js.map
```
There is no `chance.min.js.map` file in the extension, but it is referenced in `chance.min.js`:
```
//# sourceMappingURL=chance.min.js.map
```
Please remove this line or add in the actual source map if you feel it's necessary.

**Comment by ptomaszek** [comment]
Fixed in version 1.3.1
