### ISSUE TITLE
Doesn't populate selects

### ISSUE THREAD

**Issue by migig** [ptomaszek/dummy-form-filler#6]
This is not populated:

    <select>
      <option value="0" selected="selected">None</option>
      <option value="1">Foo</option>
      <option value="2">Bar</option>
      <option value="3">Baz</option>
    </select>

Neither is this:

    <select>
      <option value="0"></option>
      <option value="1">Foo</option>
      <option value="2">Bar</option>
      <option value="3">Baz</option>
    </select>

Otherwise, a great dev tool. I like the "lack of features" feature! :)

**Comment by ptomaszek** [comment]
Well, what you've raised was not considered by me as a bug. But after thinking for a minute about the issue I had to assume that you're right (at least in one case)!

DFF will choose some options when the currently selected option:
1. has empty option content:
```
<select>
  <option value="0"></option>
  <option value="1">Foo</option>
</select>
```
2. is disabled:
```
<select>
        <option value="volvo">Volvo</option>
        <option disabled selected> -- select an option --</option>
</select> 
```

For now I don't think the 'None' option should be considered as a non-valid option so the DFF won't work for your first example.

For now the fix is in develop branch only. Update will be pushed on addons.mozilla.org the next week.

Thanks for your concern and kind words.

**Comment by ptomaszek** [comment]
Well, what you've raised was not considered by me as a bug. But after thinking for a minute about the issue I had to assume that you're right (at least in one case)!

DFF will choose some options when the currently selected option:
* has empty option content:
```html
<select>
  <option value="0"></option>
  <option value="1">Foo</option>
</select>
```

* is disabled:
```html

<select>
        <option value="volvo">Volvo</option>
        <option disabled selected> -- select an option --</option>
</select> 
```

For now I don't think the 'None' option should be considered as a non-valid option so the DFF won't work for your first example.

For now the fix is in develop branch only. Update will be pushed on addons.mozilla.org the next week.

Thanks for your concern and kind words.

**Comment by ptomaszek** [comment]
Fixed in 0.11.

**Comment by migig** [comment]
Thanks for the changes! Works 100x better now. :)

BUT... The behavior is not consistent. If you click again, it repopulates the form, as well as all selects.

So, it should populate selects on first click as well, regardless of what was already selected.What do you think?

**Comment by ptomaszek** [comment]
I'm glad it's better now.

Your's argument 'most modern selects will have a "Please select one the following options..."' is very convincing. Current 'select behavior' may not meet expectations of every user. I think that introducing some 'Options' panel with basic settings could satisfy people's different needs: 
```
Select a 'select' element when: 
 * always (ignore and clear already selected options)
 * current option is disabled
 * current option's value is empty
 * current option's value contains words: x, y, z
Don't touch already populated 'input' elements: on/off
<etc.>
```

Sadly, as the 'Options' would be something totally new, I may not be able to code it too soon. On the other hand the 'Options' solution may get over-engineered and therefore loosing the 'Lack of features' feature will be a disaster. 

For the summary - let me leave the add-on as it is for now and I'll try to go back on it when I have more time or receive more feedback.

**Comment by migig** [comment]
OK :)

I agree adding an options panel is completely unnecessary. That means the behavior should meet your personal needs, and my suggestion obviously doesn't. Which is cool. It's your code after all.

I'll carry on using it though, other than the select issue, it works great.

(And I can't find anything remotely similar which does all this, and populates the selects, so your plugin is the winner.)

**Comment by ptomaszek** [comment]
In v0.12 the add-on will decide that sometimes selected 'select' is in fact unselected. This example describes it:
```
    Already selected but contains strings like 'select, choose, pick' so is considered to be unselected yet and another option will be picked (1, 2 or 4):
    <select>
        <option value="volvo">Volvo</option>
        <option value="saab">Saab</option>
        <option selected value="nothing">Choose your destiny!</option>
        <option value="audi">Audi</option>
    </select>
```

**Comment by ptomaszek** [comment]
And it's been released.

**Comment by migig** [comment]
If you're still tinkering with this then consider this use case. As in my original example often you'll have a list of `<option>`s with indexes:

<select>
  <option value="0" selected="selected">Country?</option>
  <option value="1">US</option>
  <option value="2">Canada</option>
  <option value="3">Mexico</option>
</select>

So your current change will work, if the zeroth element had "None" or "Select" or some similar keyword. But most `select`s don't, they would rather describe the content of that dropdown.

Your original response was that this was simply not a use case you cared about. But then you've made some changes, so I'm thinking that maybe I'll convince you yet.

The trick to get this one working is to inspect the value. Most dropdowns start at `1`. A dropdown which starts at `0` is typically going to contain a "please select" option as its zeroth option.

Of course this is not strictly the case all the time. But most of the time. And besides, if you don't like the value, hit the button again!

Think about it.
