### ISSUE TITLE
The add-on is not working - jas891's issue

### ISSUE THREAD

**Issue by ptomaszek** [ptomaszek/dummy-form-filler#9]
Hi jas891,

Please open the following page and tell me whether the add-on works: http://www.webdevout.net/test?02Z&raw

We'll go further from there.

**Comment by jas891** [comment]
That page does work. Here is one that used to work for me but now it doesnt:
https://k-ltd.applicantstack.com/x/apply/a2117acd2hqm

As you can see, this plugin is a big help when testing these forms.

**Comment by ptomaszek** [comment]
Thank for the link. Seems like there's something wrong with latest version 0.12.

Until I fix it, please use v0.11 -
https://addons.mozilla.org/en-US/firefox/addon/dummy-form-filler/versions/?page=1#version-0.11

**Comment by ptomaszek** [comment]
Version 0.12.1 that fixes the problem has been released https://addons.mozilla.org/en-US/firefox/addon/dummy-form-filler/versions/?page=1#version-0.12.1

One more digression:
On the page you're testing I see some fields (email, phone name and so on) are not being populated as expected. I'll try to check whether it'll be ease to optimize the add-on so it would work better for those fields.
